# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      # https://stackoverflow.com/questions/68211182/how-to-set-system-path-variable-in-github-action-workflow
      - run: echo %PNPM_HOME% >> $GITHUB_PATH
        if: startsWith(matrix.config.os, 'windows')

      - name: Add to PATH
        if: startsWith(matrix.config.os, 'windows')
        shell: pwsh
        run: |
          echo %PNPM_HOME% | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - run: echo %PATH%
        if: startsWith(matrix.config.os, 'windows')

      - run: pnpm add -g @constl/ipa @constl/serveur

      - run: where constl
        if: startsWith(matrix.config.os, 'windows')

      - run: ls C:\Users\runneradmin
        if: startsWith(matrix.config.os, 'windows')



      - run: ls C:\Users\runneradmin\setup-pnpm
        if: startsWith(matrix.config.os, 'windows')



      - run: ls C:\Users\runneradmin\setup-pnpm\node_modules
        if: startsWith(matrix.config.os, 'windows')


      - run: constl v-constl

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck

      - uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
